In [1]:
import numpy as npy

In [2]:
def sigmoid(x):
    return 1/(1+npy.exp(-x))
print(sigmoid(0.5))

0.6224593312018546


In [3]:
def gradient(x):
    return sigmoid(x)/(1-sigmoid(x))

print(gradient(0.5))

1.6487212707001284


In [4]:
def image2vector(x):
    return x.reshape(x.shape[2]*x.shape[1]*x.shape[0],1)
a=npy.zeros((2,2,3))
print(a)
print(image2vector(a))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [5]:
def normalizeRows(x):
    x_norm = npy.linalg.norm(x, axis = 1, keepdims = True)
    return x / x_norm
x=[[1,2],[3,4]]
normalizeRows(x)

array([[0.4472136 , 0.89442719],
       [0.6       , 0.8       ]])

In [14]:
def Lf1(visual,really):
    return sum(abs((npy.subtract(visual,really))))
def Lf2(T,really):
    return sum(npy.power(npy.subtract(visual,really),2))
visual=[5,5,5]
really=[3,0,1]
print(Lf1(visual,really))
print(Lf2(visual,really))

11
45
